# Generated by Django 5.2.8 on 2025-11-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(default='Não informado/ Gerais', max_length=100),
        ),
    ]
