# Generated by Django 5.2.8 on 2025-11-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type_expense',
            field=models.CharField(choices=[('à vista', 'à vista'), ('parcelado', 'parcelado'), ('mensal', 'mensal')], default='à vista'),
        ),
    ]
