# Generated by Django 5.2.8 on 2025-11-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0002_alter_expense_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_installments', models.IntegerField(default=2)),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expense')),
            ],
        ),
    ]
